import telebot
from telebot import types
import openpyxl
import schedule
import time
import threading
#331340889
bot = telebot.TeleBot('1128991423:AAHSBnWSw1h5J2m6lOLiuwETy1Xa3U5JMDc')
wb=openpyxl.load_workbook("films.xlsx")
sheet=wb.active
def send_message():
    bot.send_sticker(458392375,'CAACAgIAAxkBAAIKXV_Y_y2j0w91lsiuBo1E4t4fR49kAAKwBAACZdzeB1Tz4HubzWvDHgQ')
    bot.send_message(458392375, text='Топ фільмів на сьогодні :)')
    bot.send_message( 458392375,text='https://www.bbc.com/ukrainian/vert-cul-53363124')

def send_message1():
    bot.send_sticker(331340889,'CAACAgIAAxkBAAIKXV_Y_y2j0w91lsiuBo1E4t4fR49kAAKwBAACZdzeB1Tz4HubzWvDHgQ')
    bot.send_message(331340889, text='Топ фільмів на сьогодні :)')
    bot.send_message( 331340889,text='https://www.bbc.com/ukrainian/vert-cul-53363124')

schedule.every().day.at("20:31").do(send_message)
schedule.every().day.at("20:31").do(send_message1)

def go():
    while 1:
        schedule.run_pending()
        time.sleep(1)

t = threading.Thread(target=go, name="тест")
t.start()

@bot.message_handler(commands=['info'])
def choose_lang(message):
    bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIEEl-zwdshKKuA-t5_ZhMb0SxwsBngAAJqBAACZdzeB1v3vJ7YxGBJHgQ')
    keyboard = types.InlineKeyboardMarkup()
    key_ukr = types.InlineKeyboardButton(text='Українська', callback_data='ukrlanguage')
    keyboard.add(key_ukr)
    key_eng = types.InlineKeyboardButton(text='English', callback_data='englanguage')
    keyboard.add(key_eng)
    bot.send_message(message.chat.id, "Виберіть мову\nChoose a language", reply_markup=keyboard)


@bot.callback_query_handler(func=lambda call: True)
def callback_lang(call):
    if call.data == "ukrlanguage":
        bot.send_sticker(call.message.chat.id, 'CAACAgIAAxkBAAIEKl-zwrOVt7t7pfangLkNjOCNN1FAAAK4BAACZdzeB2JVlRS0h01THgQ')
        markup_reply = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_chfilm = types.KeyboardButton('Обрати фільм самостійно')
        key_filmlist = types.KeyboardButton('Топ фільмів 📝')
        key_seriallist = types.KeyboardButton('Топ серіалів')
        markup_reply.add(key_filmlist, key_chfilm, key_seriallist)
        bot.send_message(call.message.chat.id, text="Давай спілкуватись українською! ;)")
        bot.send_message(call.message.chat.id, text="Обери дію 👇🏻", reply_markup=markup_reply)
    elif call.data == "englanguage":
        bot.send_sticker(call.message.chat.id, 'CAACAgIAAxkBAAIEKl-zwrOVt7t7pfangLkNjOCNN1FAAAK4BAACZdzeB2JVlRS0h01THgQ')
        markup_reply1 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_chfilm1 = types.KeyboardButton('Choose a movie by yourself')
        key_filmlist1 = types.KeyboardButton('List of films')
        key_seriallist1 = types.KeyboardButton('List of TV shows')
        markup_reply1.add(key_filmlist1, key_chfilm1, key_seriallist1)
        bot.send_message(call.message.chat.id, text="Let's speak in English! ;)")
        bot.send_message(call.message.chat.id, text="Choose what you want to do 👇🏻", reply_markup=markup_reply1)
    elif call.data == "com":
        bot.send_sticker(call.message.chat.id, 'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply2 = types.ReplyKeyboardMarkup(resize_keyboard=True)
        key_top = types.KeyboardButton('ТОП комедій')
        key_prod = types.KeyboardButton('Продовжити обирати комедію')
        markup_reply2.add(key_top, key_prod)
        bot.send_message(call.message.chat.id, text="Обери дію 👇🏻", reply_markup=markup_reply2)
    elif call.data == "com1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply3 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top1 = types.KeyboardButton('TOP comedies')
        key_prod1 = types.KeyboardButton('Continue to choose a comedy')
        markup_reply3.add(key_top1, key_prod1)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_reply3)
    elif call.data == "ist":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply4 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top2 = types.KeyboardButton('ТОП історичних')
        key_prod2 = types.KeyboardButton('Продовжити обирати історичний фільм')
        markup_reply4.add(key_top2, key_prod2)
        bot.send_message(call.message.chat.id, text="Обери дію 👇🏻", reply_markup=markup_reply4)
    elif call.data == "ist1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply5 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top3 = types.KeyboardButton('TOP historicals')
        key_prod3 = types.KeyboardButton('Continue to choose a historical')
        markup_reply5.add(key_top3, key_prod3)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_reply5)
    elif call.data == "hor":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply6 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top4 = types.KeyboardButton('ТОП жахи')
        key_prod4 = types.KeyboardButton('Продовжити обирати фільм жахів')
        markup_reply6.add(key_top4, key_prod4)
        bot.send_message(call.message.chat.id, text="Обери дію 👇🏻", reply_markup=markup_reply6)
    elif call.data == "hor1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply7 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top5 = types.KeyboardButton('TOP horrors')
        key_prod5 = types.KeyboardButton('Continue to choose a horror')
        markup_reply7.add(key_top5, key_prod5)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_reply7)
    elif call.data == "mel":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply8 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top6 = types.KeyboardButton('ТОП мелодрам')
        key_prod6 = types.KeyboardButton('Продовжити обирати мелодраму')
        markup_reply8.add(key_top6, key_prod6)
        bot.send_message(call.message.chat.id, text="Обери дію 👇🏻", reply_markup=markup_reply8)
    elif call.data == "mel1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply9 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top7 = types.KeyboardButton('TOP melodramas')
        key_prod7 = types.KeyboardButton('Continue to choose a melodrama')
        markup_reply9.add(key_top7, key_prod7)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_reply9)
    elif call.data == "doc":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply10 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top8 = types.KeyboardButton('ТОП документальні')
        key_prod8 = types.KeyboardButton('Продовжити обирати документальний фільм')
        markup_reply10.add(key_top8, key_prod8)
        bot.send_message(call.message.chat.id, text="Обери дію 👇🏻", reply_markup=markup_reply10)
    elif call.data == "doc1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply11 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top9 = types.KeyboardButton('TOP non-fictions')
        key_prod9 = types.KeyboardButton('Continue to choose a non-fiction')
        markup_reply11.add(key_top9, key_prod9)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_reply11)
    elif call.data == "pryg":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply12 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top10 = types.KeyboardButton('ТОП пригодницькі')
        key_prod10 = types.KeyboardButton('Продовжити обирати пригодницький фільм')
        markup_reply12.add(key_top10, key_prod10)
        bot.send_message(call.message.chat.id, text="Обери дію 👇🏻", reply_markup=markup_reply12)
    elif call.data == "pryg1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply13 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top11 = types.KeyboardButton('TOP adventures')
        key_prod11 = types.KeyboardButton('Continue to choose an adventure')
        markup_reply13.add(key_top11, key_prod11)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_reply13)
    elif call.data == "boy":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply14 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top12 = types.KeyboardButton('ТОП бойовиків')
        key_prod12 = types.KeyboardButton('Продовжити обирати бойовик')
        markup_reply14.add(key_top12, key_prod12)
        bot.send_message(call.message.chat.id, text="Обери дію 👇🏻", reply_markup=markup_reply14)
    elif call.data == "boy1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply15 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top13 = types.KeyboardButton('TOP actions')
        key_prod13 = types.KeyboardButton('Continue to choose an action')
        markup_reply15.add(key_top13, key_prod13)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_reply15)
    elif call.data == "fan":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply16 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top14 = types.KeyboardButton('ТОП фантастика')
        key_prod14 = types.KeyboardButton('Продовжити обирати фантастику')
        markup_reply16.add(key_top14, key_prod14)
        bot.send_message(call.message.chat.id, text="Обери дію 👇🏻", reply_markup=markup_reply16)
    elif call.data == "fan1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply17 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top15 = types.KeyboardButton('TOP fantasy')
        key_prod15 = types.KeyboardButton('Continue to choose a fantasy')
        markup_reply17.add(key_top15, key_prod15)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_reply17)
    elif call.data == "dram":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply18 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top16 = types.KeyboardButton('ТОП драми')
        key_prod16 = types.KeyboardButton('Продовжити обирати драму')
        markup_reply18.add(key_top16, key_prod16)
        bot.send_message(call.message.chat.id, text="Обери дію 👇🏻", reply_markup=markup_reply18)
    elif call.data == "dram1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply19 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top17 = types.KeyboardButton('TOP dramas')
        key_prod17 = types.KeyboardButton('Continue to choose a drama')
        markup_reply19.add(key_top17, key_prod17)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_reply19)
    elif call.data == "tryl":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply20 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top18 = types.KeyboardButton('ТОП трилери')
        key_prod18 = types.KeyboardButton('Продовжити обирати трилер')
        markup_reply20.add(key_top18, key_prod18)
        bot.send_message(call.message.chat.id, text="Обери дію 👇🏻", reply_markup=markup_reply20)
    elif call.data == "tryl1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply21 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top19 = types.KeyboardButton('TOP thrillers')
        key_prod19 = types.KeyboardButton('Continue to choose a thriller')
        markup_reply21.add(key_top19, key_prod19)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_reply21)
    elif call.data == "mis":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply22 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top20 = types.KeyboardButton('ТОП містика')
        key_prod20 = types.KeyboardButton('Продовжити обирати містику')
        markup_reply22.add(key_top20, key_prod20)
        bot.send_message(call.message.chat.id, text="Обери дію 👇🏻", reply_markup=markup_reply22)
    elif call.data == "mis1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIICV_UqQSrn7fr4R1VlrjhVicV6_A7AAJqBAACZdzeB1v3vJ7YxGBJHgQ')
        markup_reply23 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key_top21 = types.KeyboardButton('TOP mysteries')
        key_prod21 = types.KeyboardButton('Continue to choose a mystery')
        markup_reply23.add(key_top21, key_prod21)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_reply23)
    elif call.data == "ycom1":
        bot.send_sticker(call.message.chat.id, 'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AE']:
            bot.send_message(call.message.chat.id,  cell.value  )
        markup_rep1 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key01 = types.KeyboardButton('Обрати інший фільм')
        key100 = types.KeyboardButton('Завершити!')
        markup_rep1.add(key01,key100)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep1)
    elif call.data == "ycom2":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AF']:
            bot.send_message(call.message.chat.id,  cell.value  )
        markup_rep = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key01 = types.KeyboardButton('Обрати інший фільм')
        key101 = types.KeyboardButton('Завершити!')
        markup_rep.add(key01,key101)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep)
    elif call.data == "ycom3":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AG']:
            bot.send_message(call.message.chat.id,  cell.value  )
        markup_rep2 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key03 = types.KeyboardButton('Обрати інший фільм')
        key102 = types.KeyboardButton('Завершити!')
        markup_rep2.add(key03,key102)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep2)
    elif call.data == "ycom11":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['A']:
            bot.send_message(call.message.chat.id,  cell.value  )
        markup_rep0 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key02 = types.KeyboardButton('Choose another movie')
        key103 = types.KeyboardButton('Finish!')
        markup_rep0.add(key02,key103)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep0)
    elif call.data == "ycom12":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['B']:
            bot.send_message(call.message.chat.id,  cell.value  )
        markup_rep3 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key04 = types.KeyboardButton('Choose another movie')
        key104 = types.KeyboardButton('Finish!')
        markup_rep3.add(key04,key104)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep3)
    elif call.data == "ycom13":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['C']:
            bot.send_message(call.message.chat.id,  cell.value  )
        markup_rep4 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key05 = types.KeyboardButton('Choose another movie')
        key105 = types.KeyboardButton('Finish!')
        markup_rep4.add(key05,key105)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep4)
    elif call.data == "yist1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['BI']:
            bot.send_message(call.message.chat.id,  cell.value  )
        markup_rep5 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key06 = types.KeyboardButton('Обрати інший фільм')
        key106 = types.KeyboardButton('Завершити!')
        markup_rep5.add(key06,key106)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep5)
    elif call.data == "yist2":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['BJ']:
            bot.send_message(call.message.chat.id,  cell.value  )
        markup_rep6 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key07 = types.KeyboardButton('Обрати інший фільм')
        key107 = types.KeyboardButton('Завершити!')
        markup_rep6.add(key07,key107)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep6)
    elif call.data == "yist3":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['BK']:
            bot.send_message(call.message.chat.id,  cell.value  )
        markup_rep7 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key08 = types.KeyboardButton('Обрати інший фільм')
        key108 = types.KeyboardButton('Завершити!')
        markup_rep7.add(key08,key108)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep7)
    elif call.data == "yist11":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['BL']:
            bot.send_message(call.message.chat.id,  cell.value  )
        markup_rep8 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key09 = types.KeyboardButton('Choose another movie')
        key109 = types.KeyboardButton('Finish!')
        markup_rep8.add(key09,key109)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep8)
    elif call.data == "yist12":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['BM']:
            bot.send_message(call.message.chat.id,  cell.value  )
        markup_rep9 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key010 = types.KeyboardButton('Choose another movie')
        key110 = types.KeyboardButton('Finish!')
        markup_rep9.add(key010,key110)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep9)
    elif call.data == "yist13":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['BN']:
            bot.send_message(call.message.chat.id,  cell.value  )
        markup_rep10 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key011 = types.KeyboardButton('Choose another movie')
        key111 = types.KeyboardButton('Finish!')
        markup_rep10.add(key011)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep10)
    elif call.data == "yhor1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AH']:
            bot.send_message(call.message.chat.id,  cell.value  )
        markup_rep11 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key012 = types.KeyboardButton('Обрати інший фільм')
        key112 = types.KeyboardButton('Завершити!')
        markup_rep11.add(key012, key112)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep11)
    elif call.data == "yhor2":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AI']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep12 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key013 = types.KeyboardButton('Обрати інший фільм')
        key113 = types.KeyboardButton('Завершити!')
        markup_rep12.add(key013,key113)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep12)
    elif call.data == "yhor3":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AJ']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep13 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key014 = types.KeyboardButton('Обрати інший фільм')
        key114 = types.KeyboardButton('Завершити!')
        markup_rep13.add(key014, key114)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep13)
    elif call.data == "yhor11":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['D']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep14 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key015 = types.KeyboardButton('Choose another movie')
        key115 = types.KeyboardButton('Finish!')
        markup_rep14.add(key015,key115)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep14)
    elif call.data == "yhor12":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['E']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep15 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key016 = types.KeyboardButton('Choose another movie')
        key116 = types.KeyboardButton('Finish!')
        markup_rep15.add(key016, key116)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep15)
    elif call.data == "yhor13":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['F']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep16 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key017 = types.KeyboardButton('Choose another movie')
        key117 = types.KeyboardButton('Finish!')
        markup_rep16.add(key017,key117)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep16)
    elif call.data == "ymel1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AZ']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep17 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key018 = types.KeyboardButton('Обрати інший фільм')
        key118 = types.KeyboardButton('Завершити!')
        markup_rep17.add(key018, key118)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep17)
    elif call.data == "ymel2":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['BA']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep18 = types.ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)
        key019 = types.KeyboardButton('Обрати інший фільм')
        key119 = types.KeyboardButton('Завершити!')
        markup_rep18.add(key019, key119)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep18)
    elif call.data == "ymel3":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['BB']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep19 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key020 = types.KeyboardButton('Обрати інший фільм')
        key1191 = types.KeyboardButton('Завершити!')
        markup_rep19.add(key020,key1191)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep19)
    elif call.data == "ymel11":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['V']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep20 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key021 = types.KeyboardButton('Choose another movie')
        key1192 = types.KeyboardButton('Finish!')
        markup_rep20.add(key021,key1192)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep20)
    elif call.data == "ymel12":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['W']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep21 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key022 = types.KeyboardButton('Choose another movie')
        key1193 = types.KeyboardButton('Finish!')
        markup_rep21.add(key022, key1193)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep21)
    elif call.data == "ymel13":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['X']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep22 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key023 = types.KeyboardButton('Choose another movie')
        key1194 = types.KeyboardButton('Finish!')
        markup_rep22.add(key023, key1194)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep22)
    elif call.data == "ydoc1":
        bot.send_sticker(call.message.chat.id, 'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['BC']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep23 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key024 = types.KeyboardButton('Обрати інший фільм')
        key1195 = types.KeyboardButton('Завершити!')
        markup_rep23.add(key024,key1195)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep23)
    elif call.data == "ydoc2":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['BD']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep24 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key025 = types.KeyboardButton('Обрати інший фільм')
        key1196 = types.KeyboardButton('Завершити!')
        markup_rep24.add(key025,key1196)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep24)
    elif call.data == "ydoc3":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['BE']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep25 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key026 = types.KeyboardButton('Обрати інший фільм')
        key1197 = types.KeyboardButton('Завершити!')
        markup_rep25.add(key026,key1197)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep25)
    elif call.data == "ydoc11":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['Y']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep26 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key027 = types.KeyboardButton('Choose another movie')
        key1198 = types.KeyboardButton('Finish!')
        markup_rep26.add(key027,key1198)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep26)
    elif call.data == "ydoc12":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['Z']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep27 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key028 = types.KeyboardButton('Choose another movie')
        key1199 = types.KeyboardButton('Finish!')
        markup_rep27.add(key028,key1199)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep27)
    elif call.data == "ydoc13":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['AA']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep28 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key029 = types.KeyboardButton('Choose another movie')
        key1110 = types.KeyboardButton('Finish!')
        markup_rep28.add(key029,key1110)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep28)
    elif call.data == "ypryg1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['BF']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep29 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key030 = types.KeyboardButton('Обрати інший фільм')
        key1111 = types.KeyboardButton('Завершити!')
        markup_rep29.add(key030,key1111)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep29)
    elif call.data == "ypryg2":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['BG']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep30 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key031 = types.KeyboardButton('Обрати інший фільм')
        key1112 = types.KeyboardButton('Завершити!')
        markup_rep30.add(key031,key1112)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep30)
    elif call.data == "ypryg3":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['BH']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep31 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key032 = types.KeyboardButton('Обрати інший фільм')
        key1113 = types.KeyboardButton('Завершити!')
        markup_rep31.add(key032,key1113)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep31)
    elif call.data == "ypryg11":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['AB']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep32 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key033 = types.KeyboardButton('Choose another movie')
        key1114 = types.KeyboardButton('Finish!')
        markup_rep32.add(key033,key1114)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep32)
    elif call.data == "ypryg12":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['AC']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep33 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key034 = types.KeyboardButton('Choose another movie')
        key1115 = types.KeyboardButton('Finish!')
        markup_rep33.add(key034,key1115)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep33)
    elif call.data == "ypryg13":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['AD']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep34 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key035 = types.KeyboardButton('Choose another movie')
        key1116 = types.KeyboardButton('Finish!')
        markup_rep34.add(key035,key1116)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep34)
    elif call.data == "yboy1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AK']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep35 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key036 = types.KeyboardButton('Обрати інший фільм')
        key1117 = types.KeyboardButton('Завершити!')
        markup_rep35.add(key036,key1117)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep35)
    elif call.data == "yboy2":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AL']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep36 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key037 = types.KeyboardButton('Обрати інший фільм')
        key1118 = types.KeyboardButton('Завершити!')
        markup_rep36.add(key037,key1118)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep36)
    elif call.data == "yboy3":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AM']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep37 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key038 = types.KeyboardButton('Обрати інший фільм')
        key1119 = types.KeyboardButton('Завершити!')
        markup_rep37.add(key038, key1119)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep37)
    elif call.data == "yboy11":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['G']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep38 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key039 = types.KeyboardButton('Choose another movie')
        key121 = types.KeyboardButton('Finish!')
        markup_rep38.add(key039,key121)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep38)
    elif call.data == "yboy12":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['H']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep39 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key040 = types.KeyboardButton('Choose another movie')
        key122 = types.KeyboardButton('Finish!')
        markup_rep39.add(key040, key122)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep39)
    elif call.data == "yboy13":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['I']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep40 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key041 = types.KeyboardButton('Choose another movie')
        key123 = types.KeyboardButton('Finish!')
        markup_rep40.add(key041,key123)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep40)
    elif call.data == "yfan1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AN']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep41 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key042 = types.KeyboardButton('Обрати інший фільм')
        key130 = types.KeyboardButton('Завершити!')
        markup_rep41.add(key042,key130)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep41)
    elif call.data == "yfan2":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AO']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep42 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key043 = types.KeyboardButton('Обрати інший фільм')
        key131 = types.KeyboardButton('Завершити!')
        markup_rep42.add(key043,key131)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep42)
    elif call.data == "yfan3":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AP']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep43 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key044 = types.KeyboardButton('Обрати інший фільм')
        key132 = types.KeyboardButton('Завершити!')
        markup_rep43.add(key044,key132)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep43)
    elif call.data == "yfan11":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['J']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep44 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key045 = types.KeyboardButton('Choose another movie')
        key133 = types.KeyboardButton('Finish!')
        markup_rep44.add(key045,key133)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep44)
    elif call.data == "yfan12":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['K']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep45 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key046 = types.KeyboardButton('Choose another movie')
        key134 = types.KeyboardButton('Finish!')
        markup_rep45.add(key046)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep45)
    elif call.data == "yfan13":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['L']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep46 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key047 = types.KeyboardButton('Choose another movie')
        key135 = types.KeyboardButton('Finish!')
        markup_rep46.add(key047)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep46)
    elif call.data == "ydram1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AQ']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep47 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key048 = types.KeyboardButton('Обрати інший фільм')
        key136 = types.KeyboardButton('Завершити!')
        markup_rep47.add(key048,key136)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep47)
    elif call.data == "ydram2":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AR']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep48 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key049 = types.KeyboardButton('Обрати інший фільм')
        key137 = types.KeyboardButton('Завершити!')
        markup_rep48.add(key049,key137)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep48)
    elif call.data == "ydram3":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AS']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep49 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key050 = types.KeyboardButton('Обрати інший фільм')
        key070 = types.KeyboardButton('Завершити!')
        markup_rep49.add(key050)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep49)
    elif call.data == "ydram11":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['M']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep50 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key066 = types.KeyboardButton('Choose another movie')
        key140 = types.KeyboardButton('Finish!')
        markup_rep50.add(key066)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep50)
    elif call.data == "ydram12":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['N']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep51 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key067 = types.KeyboardButton('Choose another movie')
        key070 = types.KeyboardButton('Finish!')
        markup_rep51.add(key067)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep51)
    elif call.data == "ydram13":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['O']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep52 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key051 = types.KeyboardButton('Choose another movie')
        key141 = types.KeyboardButton('Finish!')
        markup_rep52.add(key051)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep52)
    elif call.data == "ytryl1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AT']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep53 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key052= types.KeyboardButton('Обрати інший фільм')
        key142 = types.KeyboardButton('Завершити!')
        markup_rep53.add(key052,key142)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep53)
    elif call.data == "ytryl2":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.from_user.id, text='Приємного перелгяду ;)')
        for cell in sheet['AU']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep54 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key053 = types.KeyboardButton('Обрати інший фільм')
        key143 = types.KeyboardButton('Завершити!')
        markup_rep54.add(key053,key143)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep54)
    elif call.data == "ytryl3":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AV']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep55 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key054 = types.KeyboardButton('Обрати інший фільм')
        key144 = types.KeyboardButton('Завершити!')
        markup_rep55.add(key054,key144)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep55)
    elif call.data == "ytryl11":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['P']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep56 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key055 = types.KeyboardButton('Choose another movie')
        key145 = types.KeyboardButton('Finish!')
        markup_rep56.add(key055,key145)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep56)
    elif call.data == "ytryl12":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['Q']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep57 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key058 = types.KeyboardButton('Choose another movie')
        key146 = types.KeyboardButton('Finish!')
        markup_rep57.add(key058,key146)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep57)
    elif call.data == "ytryl13":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['R']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep58 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key059 = types.KeyboardButton('Choose another movie')
        key147 = types.KeyboardButton('Finish!')
        markup_rep58.add(key059,key147)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep58)
    elif call.data == "ymis1":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AW']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep59 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key060 = types.KeyboardButton('Обрати інший фільм')
        key148 = types.KeyboardButton('Завершити!')
        markup_rep59.add(key060,key148)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep59)
    elif call.data == "ymis2":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AX']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep60 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key061 = types.KeyboardButton('Обрати інший фільм')
        key149 = types.KeyboardButton('Завершити!')
        markup_rep60.add(key061,key149)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep60)
    elif call.data == "ymis3":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Приємного перегляду ;)')
        for cell in sheet['AY']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep61 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key062 = types.KeyboardButton('Обрати інший фільм')
        key150 = types.KeyboardButton('Завершити!')
        markup_rep61.add(key062,key150)
        bot.send_message(call.message.chat.id, text="Оберіть дію 👇🏻", reply_markup=markup_rep61)
    elif call.data == "ymis11":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['S']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep62 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key063 = types.KeyboardButton('Choose another movie')
        key151 = types.KeyboardButton('Finish!')
        markup_rep62.add(key063,key151)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep62)
    elif call.data == "ymis12":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['T']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep63 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key064 = types.KeyboardButton('Choose another movie')
        key152 = types.KeyboardButton('Finish!')
        markup_rep63.add(key064,key152)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep63)
    elif call.data == "ymis13":
        bot.send_sticker(call.message.chat.id,'CAACAgIAAxkBAAIIMF_WRq4w7e3fKPglO_GWqsDIT3hkAAJnBAACZdzeB7ECzSUNmxKlHgQ')
        bot.send_message(call.message.chat.id, text='Enjoy ;)')
        for cell in sheet['U']:
            bot.send_message(call.message.chat.id, cell.value)
        markup_rep64 = types.ReplyKeyboardMarkup(resize_keyboard=True,one_time_keyboard=True)
        key065 = types.KeyboardButton('Choose another movie')
        key153 = types.KeyboardButton('Finish!')
        markup_rep64.add(key065,key153)
        bot.send_message(call.message.chat.id, text="Choose an action 👇🏻", reply_markup=markup_rep64)



@bot.message_handler(content_types=['text'])
def user_choose(message):
    if message.text == 'Finish!':
        bot.send_sticker(message.chat.id,'CAACAgIAAxkBAAIIVF_XuGWzdstZ1rpzkYozWNayqolHAAJoBAACZdzeB7BqN8QLhSaWHgQ')
        bot.send_message(message.from_user.id, text='Bye!')
    elif message.text == 'Завершити!':
        bot.send_sticker(message.chat.id,'CAACAgIAAxkBAAIIVF_XuGWzdstZ1rpzkYozWNayqolHAAJoBAACZdzeB7BqN8QLhSaWHgQ')
        bot.send_message(message.from_user.id, text='Бувай!')
    elif message.text == 'Продовжити обирати комедію':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard10 = types.InlineKeyboardMarkup()
        key_yearcom1 = types.InlineKeyboardButton(text='1990-2000', callback_data='ycom1')
        key_yearcom2 = types.InlineKeyboardButton(text='2000-2010', callback_data='ycom2')
        key_yearcom3 = types.InlineKeyboardButton(text='2010-2020', callback_data='ycom3')
        keyboard10.add(key_yearcom1, key_yearcom2, key_yearcom3)
        bot.send_message(message.from_user.id, text='Оберіть рік 👇🏻', reply_markup=keyboard10)
    elif message.text == 'Continue to choose a comedy':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard11 = types.InlineKeyboardMarkup()
        key_yearcom11 = types.InlineKeyboardButton(text='1990-2000', callback_data='ycom11')
        key_yearcom12 = types.InlineKeyboardButton(text='2000-2010', callback_data='ycom12')
        key_yearcom13 = types.InlineKeyboardButton(text='2010-2020', callback_data='ycom13')
        keyboard11.add(key_yearcom11, key_yearcom12, key_yearcom13)
        bot.send_message(message.from_user.id, text='Choose a year 👇🏻', reply_markup=keyboard11)
    elif message.text == 'Продовжити обирати історичний фільм':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard12 = types.InlineKeyboardMarkup()
        key_yearist1 = types.InlineKeyboardButton(text='1990-2000', callback_data='yist1')
        key_yearist2 = types.InlineKeyboardButton(text='2000-2010', callback_data='yist2')
        key_yearist3 = types.InlineKeyboardButton(text='2010-2020', callback_data='yist3')
        keyboard12.add(key_yearist1, key_yearist2, key_yearist3)
        bot.send_message(message.from_user.id, text='Оберіть рік 👇🏻', reply_markup=keyboard12)
    elif message.text == 'Continue to choose a historical':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard13 = types.InlineKeyboardMarkup()
        key_yearist11 = types.InlineKeyboardButton(text='1990-2000', callback_data='yist11')
        key_yearist12 = types.InlineKeyboardButton(text='2000-2010', callback_data='yist12')
        key_yearist13 = types.InlineKeyboardButton(text='2010-2020', callback_data='yist13')
        keyboard13.add(key_yearist11, key_yearist12, key_yearist13)
        bot.send_message(message.from_user.id, text='Choose a year 👇🏻', reply_markup=keyboard13)
    elif message.text == 'Продовжити обирати фільм жахів':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard14 = types.InlineKeyboardMarkup()
        key_yearhor1 = types.InlineKeyboardButton(text='1990-2000', callback_data='yhor1')
        key_yearhor2 = types.InlineKeyboardButton(text='2000-2010', callback_data='yhor2')
        key_yearhor3 = types.InlineKeyboardButton(text='2010-2020', callback_data='yhor3')
        keyboard14.add(key_yearhor1, key_yearhor2, key_yearhor3)
        bot.send_message(message.from_user.id, text='Оберіть рік 👇🏻', reply_markup=keyboard14)
    elif message.text == 'Continue to choose a horror':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard15 = types.InlineKeyboardMarkup()
        key_yearhor11 = types.InlineKeyboardButton(text='1990-2000', callback_data='yhor11')
        key_yearhor12 = types.InlineKeyboardButton(text='2000-2010', callback_data='yhor12')
        key_yearhor13 = types.InlineKeyboardButton(text='2010-2020', callback_data='yhor13')
        keyboard15.add(key_yearhor11, key_yearhor12, key_yearhor13)
        bot.send_message(message.from_user.id, text='Choose a year 👇🏻', reply_markup=keyboard15)
    elif message.text == 'Продовжити обирати мелодраму':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard16 = types.InlineKeyboardMarkup()
        key_yearmel1 = types.InlineKeyboardButton(text='1990-2000', callback_data='ymel1')
        key_yearmel2 = types.InlineKeyboardButton(text='2000-2010', callback_data='ymel2')
        key_yearmel3 = types.InlineKeyboardButton(text='2010-2020', callback_data='ymel3')
        keyboard16.add(key_yearmel1, key_yearmel2, key_yearmel3)
        bot.send_message(message.from_user.id, text='Оберіть рік 👇🏻', reply_markup=keyboard16)
    elif message.text == 'Continue to choose a melodrama':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard17 = types.InlineKeyboardMarkup()
        key_yearmel11 = types.InlineKeyboardButton(text='1990-2000', callback_data='ymel11')
        key_yearmel12 = types.InlineKeyboardButton(text='2000-2010', callback_data='ymel12')
        key_yearmel13 = types.InlineKeyboardButton(text='2010-2020', callback_data='ymel13')
        keyboard17.add(key_yearmel11, key_yearmel12, key_yearmel13)
        bot.send_message(message.from_user.id, text='Choose a year 👇🏻', reply_markup=keyboard17)
    elif message.text == 'Продовжити обирати документальний фільм':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard18 = types.InlineKeyboardMarkup()
        key_yeardoc1 = types.InlineKeyboardButton(text='1990-2000', callback_data='ydoc1')
        key_yeardoc2 = types.InlineKeyboardButton(text='2000-2010', callback_data='ydoc2')
        key_yeardoc3 = types.InlineKeyboardButton(text='2010-2020', callback_data='ydoc3')
        keyboard18.add(key_yeardoc1, key_yeardoc2, key_yeardoc3)
        bot.send_message(message.from_user.id, text='Оберіть рік 👇🏻', reply_markup=keyboard18)
    elif message.text == 'Continue to choose a non-fiction':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard19 = types.InlineKeyboardMarkup()
        key_yeardoc11 = types.InlineKeyboardButton(text='1990-2000', callback_data='ydoc11')
        key_yeardoc12 = types.InlineKeyboardButton(text='2000-2010', callback_data='ydoc12')
        key_yeardoc13 = types.InlineKeyboardButton(text='2010-2020', callback_data='ydoc13')
        keyboard19.add(key_yeardoc11, key_yeardoc12, key_yeardoc13)
        bot.send_message(message.from_user.id, text='Choose a year 👇🏻', reply_markup=keyboard19)
    elif message.text == 'Продовжити обирати пригодницький фільм':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard20 = types.InlineKeyboardMarkup()
        key_yearpryg1 = types.InlineKeyboardButton(text='1990-2000', callback_data='ypryg1')
        key_yearpryg2 = types.InlineKeyboardButton(text='2000-2010', callback_data='ypryg2')
        key_yearpryg3 = types.InlineKeyboardButton(text='2010-2020', callback_data='ypryg3')
        keyboard20.add(key_yearpryg1, key_yearpryg2, key_yearpryg3)
        bot.send_message(message.from_user.id, text='Оберіть рік 👇🏻', reply_markup=keyboard20)
    elif message.text == 'Continue to choose an adventure':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard21 = types.InlineKeyboardMarkup()
        key_yearpryg11 = types.InlineKeyboardButton(text='1990-2000', callback_data='ypryg11')
        key_yearpryg12 = types.InlineKeyboardButton(text='2000-2010', callback_data='ypryg12')
        key_yearpryg13 = types.InlineKeyboardButton(text='2010-2020', callback_data='ypryg13')
        keyboard21.add(key_yearpryg11, key_yearpryg12, key_yearpryg13)
        bot.send_message(message.from_user.id, text='Choose a year 👇🏻', reply_markup=keyboard21)
    elif message.text == 'Продовжити обирати бойовик':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard22 = types.InlineKeyboardMarkup()
        key_yearboy1 = types.InlineKeyboardButton(text='1990-2000', callback_data='yboy1')
        key_yearboy2 = types.InlineKeyboardButton(text='2000-2010', callback_data='yboy2')
        key_yearboy3 = types.InlineKeyboardButton(text='2010-2020', callback_data='yboy3')
        keyboard22.add(key_yearboy1, key_yearboy2, key_yearboy3)
        bot.send_message(message.from_user.id, text='Оберіть рік 👇🏻', reply_markup=keyboard22)
    elif message.text == 'Continue to choose an action':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard23 = types.InlineKeyboardMarkup()
        key_yearboy11 = types.InlineKeyboardButton(text='1990-2000', callback_data='yboy11')
        key_yearboy12 = types.InlineKeyboardButton(text='2000-2010', callback_data='yboy12')
        key_yearboy13 = types.InlineKeyboardButton(text='2010-2020', callback_data='yboy13')
        keyboard23.add(key_yearboy11, key_yearboy12, key_yearboy13)
        bot.send_message(message.from_user.id, text='Choose a year 👇🏻', reply_markup=keyboard23)
    elif message.text == 'Продовжити обирати фантастику':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard24 = types.InlineKeyboardMarkup()
        key_yearfan1 = types.InlineKeyboardButton(text='1990-2000', callback_data='yfan1')
        key_yearfan2 = types.InlineKeyboardButton(text='2000-2010', callback_data='yfan2')
        key_yearfan3 = types.InlineKeyboardButton(text='2010-2020', callback_data='yfan3')
        keyboard24.add(key_yearfan1, key_yearfan2, key_yearfan3)
        bot.send_message(message.from_user.id, text='Оберіть рік 👇🏻', reply_markup=keyboard24)
    elif message.text == 'Continue to choose a fantasy':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard25 = types.InlineKeyboardMarkup()
        key_yearfan11 = types.InlineKeyboardButton(text='1990-2000', callback_data='yfan11')
        key_yearfan12 = types.InlineKeyboardButton(text='2000-2010', callback_data='yfan12')
        key_yearfan13 = types.InlineKeyboardButton(text='2010-2020', callback_data='yfan13')
        keyboard25.add(key_yearfan11, key_yearfan12, key_yearfan13)
        bot.send_message(message.from_user.id, text='Choose a year 👇🏻', reply_markup=keyboard25)
    elif message.text == 'Продовжити обирати драму':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard26 = types.InlineKeyboardMarkup()
        key_yeardram1 = types.InlineKeyboardButton(text='1990-2000', callback_data='ydram1')
        key_yeardram2 = types.InlineKeyboardButton(text='2000-2010', callback_data='ydram2')
        key_yeardram3 = types.InlineKeyboardButton(text='2010-2020', callback_data='ydram3')
        keyboard26.add(key_yeardram1, key_yeardram2, key_yeardram3)
        bot.send_message(message.from_user.id, text='Оберіть рік 👇🏻', reply_markup=keyboard26)
    elif message.text == 'Continue to choose a drama':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard27 = types.InlineKeyboardMarkup()
        key_yeardram11 = types.InlineKeyboardButton(text='1990-2000', callback_data='ydram11')
        key_yeardram12 = types.InlineKeyboardButton(text='2000-2010', callback_data='ydram12')
        key_yeardram13 = types.InlineKeyboardButton(text='2010-2020', callback_data='ydram13')
        keyboard27.add(key_yeardram11, key_yeardram12, key_yeardram13)
        bot.send_message(message.from_user.id, text='Choose a year 👇🏻', reply_markup=keyboard27)
    elif message.text == 'Продовжити обирати трилер':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard28 = types.InlineKeyboardMarkup()
        key_yeartryl1 = types.InlineKeyboardButton(text='1990-2000', callback_data='ytryl1')
        key_yeartryl2 = types.InlineKeyboardButton(text='2000-2010', callback_data='ytryl2')
        key_yeartryl3 = types.InlineKeyboardButton(text='2010-2020', callback_data='ytryl3')
        keyboard28.add(key_yeartryl1, key_yeartryl2, key_yeartryl3)
        bot.send_message(message.from_user.id, text='Оберіть рік 👇🏻', reply_markup=keyboard28)
    elif message.text == 'Continue to choose a thriller':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard29 = types.InlineKeyboardMarkup()
        key_yeartryl11 = types.InlineKeyboardButton(text='1990-2000', callback_data='ytryl11')
        key_yeartryl12 = types.InlineKeyboardButton(text='2000-2010', callback_data='ytryl12')
        key_yeartryl13 = types.InlineKeyboardButton(text='2010-2020', callback_data='ytryl13')
        keyboard29.add(key_yeartryl11, key_yeartryl12, key_yeartryl13)
        bot.send_message(message.from_user.id, text='Choose a year 👇🏻', reply_markup=keyboard29)
    elif message.text == 'Продовжити обирати містику':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard30 = types.InlineKeyboardMarkup()
        key_yearmis1 = types.InlineKeyboardButton(text='1990-2000', callback_data='ymis1')
        key_yearmis2 = types.InlineKeyboardButton(text='2000-2010', callback_data='ymis2')
        key_yearmis3 = types.InlineKeyboardButton(text='2010-2020', callback_data='ymis3')
        keyboard30.add(key_yearmis1, key_yearmis2, key_yearmis3)
        bot.send_message(message.from_user.id, text='Оберіть рік 👇🏻', reply_markup=keyboard30)
    elif message.text == 'Continue to choose a mystery':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIIl_WRYHzJHs73pQwWAcm7ee0Azg_AAJsBAACZdzeBwJymEg2FdLcHgQ')
        keyboard31 = types.InlineKeyboardMarkup()
        key_yearmis11 = types.InlineKeyboardButton(text='1990-2000', callback_data='ymis11')
        key_yearmis12 = types.InlineKeyboardButton(text='2000-2010', callback_data='ymis12')
        key_yearmis13 = types.InlineKeyboardButton(text='2010-2020', callback_data='ymis13')
        keyboard31.add(key_yearmis11, key_yearmis12, key_yearmis13)
        bot.send_message(message.from_user.id, text='Choose a year 👇🏻', reply_markup=keyboard31)
    elif message.text == 'ТОП комедій':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОП найкращих комедій")
        bot.send_message(message.from_user.id, text="https://www.google.com.ua/amp/s/ua.112.ua/kultura/krytyky-rolling-stone-nazvaly-top-50-komedii-khkhi-stolittia-454071-amp.html")
    elif message.text == 'TOP comedies':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОP best comedies")
        bot.send_message(message.from_user.id, text="https://www.google.com.ua/amp/s/www.indiewire.com/feature/best-comedy-movies-funniest-comedies-ranked-1201835289/amp/")
    elif message.text == 'ТОП історичних':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОП найкращих історичних фільмів")
        bot.send_message(message.from_user.id, text="https://www.ivi.ru/titr/goodmovies/best-historical-dramas-of-the-21st-century")
    elif message.text == 'TOP historicals':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОP best historical films")
        bot.send_message(message.from_user.id, text="https://www.google.com.ua/amp/s/www.theweek.co.uk/95946/the-ten-best-historical-movies%3famp")
    elif message.text == 'ТОП жахи':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОП найкращих фільмів жахів")
        bot.send_message(message.from_user.id, text="https://www.google.com.ua/amp/s/blog.comfy.ua/ua/20-krashhikh-filmiv-zhakhiv-yaki-varto-podivitisya_a0-76/amp/")
    elif message.text == 'TOP horrors':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОP best horrors")
        bot.send_message(message.from_user.id, text="https://editorial.rottentomatoes.com/article/the-10-scariest-horror-movies-ever/")
    elif message.text == 'ТОП мелодрам':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОП найкращих мелодрам")
        bot.send_message(message.from_user.id, text="http://www.viasat-channels.tv/blog/top-12-melodram-poslednih-let")
    elif message.text == 'TOP melodramas':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОP best melodramas")
        bot.send_message(message.from_user.id, text="https://m.imdb.com/list/ls020037441/")
    elif message.text == 'ТОП документальні':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОП найкращих документальних фільмів")
        bot.send_message(message.from_user.id, text="https://novograd.city/read/experiance/82890/dokumentalistika-vihidnogo-dnya")
    elif message.text == 'TOP non-fictions':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОP best documentaries")
        bot.send_message(message.from_user.id, text="https://m.imdb.com/list/ls062446571/")
    elif message.text == 'ТОП пригодницькі':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОП найкращих пригодницьких фільмів")
        bot.send_message(message.from_user.id, text="https://m.kinoafisha.ua/news/10-kruth-prikluacsencseskih-filmov")
    elif message.text == 'TOP adventures':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОP best adventure films")
        bot.send_message(message.from_user.id, text="https://www.google.com.ua/amp/s/amp.redbull.com/gb-en/10-movies-every-would-be-adventurer-must-see")
    elif message.text == 'ТОП бойовиків':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОП найкращих бойовиків")
        bot.send_message(message.from_user.id, text="https://paramountcomedy.ru/blog/top-17-luchshikh-boevikov-za-poslednie-desyat-let/")
    elif message.text == 'TOP actions':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОP best aсtions")
        bot.send_message(message.from_user.id, text="https://www.esquire.com/uk/culture/film/a32608333/best-action-movies/")
    elif message.text == 'ТОП фантастика':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОП найкращих фантастичних фільмів")
        bot.send_message(message.from_user.id, text="https://tripmydream.ua/media/podborki/10-fantastichnih-filmiv-jaki-vi-mogli-propystiti")
    elif message.text == 'TOP fantasy':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОP best fantasy")
        bot.send_message(message.from_user.id, text="https://m.imdb.com/list/ls009669258/")
    elif message.text == 'ТОП драми':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОП найкращих драм")
        bot.send_message(message.from_user.id, text="https://www.google.com.ua/amp/s/nv.ua/ukr/amp/kritiki-nazvali-100-krashchikh-dramatichnikh-filmiv-v-istoriji-kinematohrafa-2483346.html")
    elif message.text == 'TOP dramas':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОP best dramas")
        bot.send_message(message.from_user.id, text="https://www.rottentomatoes.com/top/bestofrt/top_100_drama_movies/")
    elif message.text == 'ТОП трилери':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОП найкращих трилерів")
        bot.send_message(message.from_user.id, text="https://www.google.com.ua/amp/s/geek.informator.ua/netflix-top-10-tryleriv-yaki-varti-vashoyi-uvagy/amp/")
    elif message.text == 'TOP thrillers':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОP best thrillers")
        bot.send_message(message.from_user.id, text="https://www.google.com.ua/amp/s/www.themanual.com/culture/best-thriller-movies/%3famp")
    elif message.text == 'ТОП містика':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОП найкращих містичних фільмів")
        bot.send_message(message.from_user.id, text="https://www.borispol.org.ua/publ/khobbi_i_razvlechenija/kino/top_10_mistichnikh_filmiv/109-1-0-888")
    elif message.text == 'TOP mysteries':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text="ТОP best mysteries films")
        bot.send_message(message.from_user.id, text="https://www.rottentomatoes.com/top/bestofrt/top_100_mystery__suspense_movies/")
    elif message.text == 'Обрати фільм самостійно' or message.text == 'Обрати інший фільм' or message.text == "Choose another movie":
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIH8l_UqAqxmSxBqUi9pPDM8fdnELAtAAKwBAACZdzeB1Tz4HubzWvDHgQ')
        keyboard1 = types.InlineKeyboardMarkup()
        key_com = types.InlineKeyboardButton(text='Комедія', callback_data='com')
        keyboard1.add(key_com)
        key_ist = types.InlineKeyboardButton(text='Історичні', callback_data='ist')
        keyboard1.add(key_ist)
        key_hor = types.InlineKeyboardButton(text='Жахи', callback_data='hor')
        keyboard1.add(key_hor)
        key_mel = types.InlineKeyboardButton(text='Мелодрами', callback_data='mel')
        keyboard1.add(key_mel)
        key_doc = types.InlineKeyboardButton(text='Документальні', callback_data='doc')
        keyboard1.add(key_doc)
        key_pryg = types.InlineKeyboardButton(text='Пригодницькі', callback_data='pryg')
        keyboard1.add(key_pryg)
        key_boy = types.InlineKeyboardButton(text='Бойовики', callback_data='boy')
        keyboard1.add(key_boy)
        key_fan = types.InlineKeyboardButton(text='Фантастика', callback_data='fan')
        keyboard1.add(key_fan)
        key_dram = types.InlineKeyboardButton(text='Драми', callback_data='dram')
        keyboard1.add(key_dram)
        key_tryl = types.InlineKeyboardButton(text='Трилери', callback_data='tryl')
        keyboard1.add(key_tryl)
        key_mis = types.InlineKeyboardButton(text='Містика', callback_data='mis')
        keyboard1.add(key_mis)
        bot.send_message(message.from_user.id, text='Оберіть жанр,який підходить вашому настрою:)',  reply_markup=keyboard1)
    elif message.text == 'Топ фільмів 📝':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text='Список фільмів:')
        bot.send_message(message.from_user.id, text='https://report.if.ua/rozvagy/23-najkrashchi-filmy-za-versiyeyu-glyadachiv-a-ne-kinokrytykiv/')
    elif message.text == 'Топ серіалів':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text='Список серіалів:')
        bot.send_message(message.from_user.id, text='https://vertigo.com.ua/top-10-continuing-series-2019/')
    elif message.text == 'List of TV shows':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIIG1_WREGGW_KEeAI13fKCX4rqKGj6AAKyBAACZdzeB37oVJ6UK0LRHgQ')
        bot.send_message(message.from_user.id, text='List of serials:')
        bot.send_message(message.from_user.id, text='https://www.cinemablend.com/television/10-Greatest-TV-Shows-All-Time-According-Hollywood-Insiders-86117.html')
    elif message.text == 'Choose a movie by yourself':
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIH8l_UqAqxmSxBqUi9pPDM8fdnELAtAAKwBAACZdzeB1Tz4HubzWvDHgQ')
        keyboard2 = types.InlineKeyboardMarkup()
        key_com1 = types.InlineKeyboardButton(text='Comedy', callback_data='com1')
        keyboard2.add(key_com1)
        key_ist1 = types.InlineKeyboardButton(text='Historical', callback_data='ist1')
        keyboard2.add(key_ist1)
        key_hor1 = types.InlineKeyboardButton(text='Horror', callback_data='hor1')
        keyboard2.add(key_hor1)
        key_mel1 = types.InlineKeyboardButton(text='MeloDrama', callback_data='mel1')
        keyboard2.add(key_mel1)
        key_doc1 = types.InlineKeyboardButton(text='Nonfictional', callback_data='doc1')
        keyboard2.add(key_doc1)
        key_pryg1 = types.InlineKeyboardButton(text='Adventure', callback_data='pryg1')
        keyboard2.add(key_pryg1)
        key_boy1 = types.InlineKeyboardButton(text='Action', callback_data='boy1')
        keyboard2.add(key_boy1)
        key_fan1 = types.InlineKeyboardButton(text='Fantasy', callback_data='fan1')
        keyboard2.add(key_fan1)
        key_dram1 = types.InlineKeyboardButton(text='Drama', callback_data='dram1')
        keyboard2.add(key_dram1)
        key_tryl1 = types.InlineKeyboardButton(text='Thriller', callback_data='tryl1')
        keyboard2.add(key_tryl1)
        key_mis1 = types.InlineKeyboardButton(text='Mystery', callback_data='mis1')
        keyboard2.add(key_mis1)
        bot.send_message(message.from_user.id, text='Choose a genre that suits to your mood:)', reply_markup=keyboard2)
    elif message.text == 'List of films':
        bot.send_message(message.from_user.id, text="List of films:")
        bot.send_message(message.from_user.id, text='https://www2.bfi.org.uk/greatest-films-all-time')
    elif message.text == "Привіт" or message.text == "Hello" or message.text == "/start":
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIED1-zwU1uBLtHebYKje6ToXIq-RWGAAJuBAACZdzeBzcJgdj2IurXHgQ')
        bot.send_message(message.from_user.id, text="Привiт, я - бот, який допоможе тобі обрати фільм, напиши /info :)\nHello, I am a bot that will help you choose a movie, write /info :)")
    elif message.text == "/help":
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIEEF-zwZwQff4mjrLOgJ8k2LOrH-YPAAJjBAACZdzeB-FjigM2N8eQHgQ')
        bot.send_message(message.from_user.id, "Напиши Привіт\nWrite Hello")
    else:
        bot.send_sticker(message.chat.id, 'CAACAgIAAxkBAAIEEV-zwcV_xby-KqrHskebyz4NBx4dAAKzBAACZdzeB_kKVzvPbW_RHgQ')
        bot.send_message(message.from_user.id, "Я тебе не розумію. Напиши /help\nI don't understand you. Write /help")


@bot.message_handler(content_types=['sticker'])
def sticker_id(message):
    print(message)


bot.polling(none_stop=True)
